### ISSUE TITLE
Upstream functionalities in O2/Framework/Logger

### ISSUE THREAD

**Issue by ktf** [FairRootGroup/FairLogger#16]
As discussed in the past, we now have a wrapper around FairLogger in:

https://github.com/AliceO2Group/AliceO2/blob/dev/Framework/Logger/include/Framework/Logger.h

in particular providing formatted output via fmt. I would like to know if you are interested in upstreaming any of this, and if yes, how you want to proceed.

**Comment by rbx** [comment]
As I have briefly mentioned [here](https://github.com/AliceO2Group/AliceO2/pull/2078#pullrequestreview-249746829) - yes, we plan to integrate it, in a similar way as your LOGF macro, but with avoiding streams (for performance benefits) and honoring our logger options (severity/verbosity/etc).
We would add fmt as a (possibly optional) dependency.
It will probably be two macros, one for printf syntax and one for fmt syntax. I rather like the LOGF name aswell, but i don't mind picking something else to avoid name clash.

**Comment by rbx** [comment]
If you like, you can already move your code here that does use streams, so you solve the formatting part and keep all logger features. This should be trivial and will solve what you want. And then i worry about adapting it to not use streams afterwards.

**Comment by ktf** [comment]
Ok, thanks. Let's rediscuss how to proceed next week. I'am now overwhelmed by something else (and by the heat wave)...

**Comment by rbx** [comment]
There is now a new release that contains the fmt functionality: v1.6.0
