### ISSUE TITLE
Handle Print() with FairLogger

### ISSUE THREAD

**Issue by TobiasStockmanns** [FairRootGroup/FairLogger#32]
Dear developers,

how do I handle the following code with the FairLogger?
```
    TParticle *p = (TParticle *)tr->GetParticle();
    std::cout << "Stage " << p->GetStatusCode() << " : ";
    p->Print();
```
The output looks like this:
`Stage 4 : TParticle: pi-            p: 0.290435 0.529053 1.184810 Vertex: 0.000000e+00 0.000000e+00 0.000000e+00    -1    -1`

I have two problems:

- `LOG(debug)` always adds a new line at the end
-  How to deal with `p->Print()`

**Comment by rbx** [comment]
One option would be to not use `TParticle::Print()`. Add `operator<<` to `TParticle`. Either by patching it in ROOT, or externally in your code, something like:
```C++
inline std::ostream& operator<<(std::ostream& os, const TParticle& p)
{
    return os << "TParticle: " << p.GetName() << " " << p.Px() << " " << p.Py() << " " << p.Pz() << " " << p.Vx() << " " << p.Vy() << " " << p.Vz() << " " << p.GetFirstMother() << " " << p.GetMother(); 
}
```

After this you can change your code to:
```C++
TParticle *p = (TParticle *)tr->GetParticle();
LOG(info) << "Stage " << p->GetStatusCode() << " : " << *p;
```
That would give you the exact same output (unless I have a typo somewhere, but you can achieve it).
Or modify it to get the output you actually want. Like, the `operator<<` could already include `p.GetStatusCode()`, remove unneeded fields, etc..

**Comment by rbx** [comment]
We could also add another macro that doesn't add a new line.

**Comment by rbx** [comment]
There is also a problem with your code. If it is called from multiple threads, the output can become mixed. This would also be the case with the no-new-line-macro. 
The `operator<<` solution doesn't have this issue.

**Comment by TobiasStockmanns** [comment]
I think it would be good to have the "no-new-line-macro" because otherwise the output could look in some cases messy.
For `p->Print()` I would go with your suggested solution of an `operator<<`.

**Comment by rbx** [comment]
The "no-new-line-macro" will not happen because of the outlined potential for threading issues it may cause. Furthermore I would avoid adding any state that is stored between LOG calls in FairLogger. And finally, as Dennis correctly pointed out in one of our meetings - a call to LOG "adds an entry in the log", which makes a new line at the end appropriate.
