### ISSUE TITLE
Missing v1.2.0 tag

### ISSUE THREAD

**Issue by kresan** [FairRootGroup/FairLogger#4]
When building dev branch, the version v.1.1.0 is installed. If I type "git log", the tag v1.2.0 is not shown. @dennisklein could you please check?

**Comment by dennisklein** [comment]
I assume your local clone existed already before the v1.2.0 release. In that case, you need to do a `git fetch --tags` or `git pull --tags` to synch the local tags with the ones from upstream.

**Comment by kresan** [comment]
I did the clone today, so after the release

**Comment by dennisklein** [comment]
Yes, you are right, the tag exists but does not point to the same commits in master or dev branch. I will fix it.

**Comment by dennisklein** [comment]
Now the tag points to the correct commit that is also tracked by `master` and `dev`. I also checked that the contents of the two different commits is the same which is the case.

**Comment by kresan** [comment]
Now it works. Thanks!
