### ISSUE TITLE
Feature: Add new log severity `detail` between `info` and `debug`

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/FairLogger#49]
Assumption in Alice is that `debug` is compiled-out in production builds. The remaining severities turn out not to be enough.

**Comment by rbx** [comment]
Additional severity is fine with me.

But just a note on:
> Assumption in Alice is that `debug` is compiled-out in production builds

What actually happens is that that they set `FAIR_MIN_SEVERITY` to `info`:
https://github.com/AliceO2Group/AliceO2/blob/dev/dependencies/O2CompileFlags.cmake#L96
So if `detail` is added between `info` and `debug`, they would have to set `FAIR_MIN_SEVERITY` to `detail` to be able to see it.
Which is also fine I guess, but worth mentioning @ktf.

**Comment by rbx** [comment]
@ktf this is now available with v1.11.0
