### ISSUE TITLE
a semicolon was inserted in the linker flags

### ISSUE THREAD

**Issue by tntakahashi** [FairRootGroup/FairLogger#53]
https://github.com/FairRootGroup/FairLogger/blob/56b90a7445dcdaa85bf92a89905df0bf72796cb0/cmake/FairLoggerLib.cmake#L131-L132
I found that in the above code, cmake inserts a semicolon in the linker flags, resulting in an error.
I suggest the following modification:
```
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,--enable-new-dtags")
    set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -Wl,--enable-new-dtags")
```

**Comment by rbx** [comment]
This is fixed in the dev branch, do you need a tag with it?
